name: ttr_updates_bot
description: A Discord bot written with nyxx and nyxx_commands.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive: ^3.3.8
  http: ^0.13.3
  intl: ^0.18.0
  io: ^1.0.4
  mongo_dart: ^0.9.1
  nyxx: ^5.1.1
  nyxx_commands: ^5.0.2
  path: ^1.8.3
  
  
  

dev_dependencies:
  lints: ^2.0.0
