name: ttr_updates_bot
description: A Discord bot written with nyxx and nyxx_commands.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  nyxx: ^4.3.0
  nyxx_commands: ^4.3.0
  
  
  

dev_dependencies:
  lints: ^2.0.0
